export default function AboutPage() {
  return (
    <div>
      <h1>About</h1>
      <p>Comic Strips can be fun and creative. This tool aims to support a 7-12 year old's creativity and to explore AI generated comic strips. 
      </p>
      <p>
      The comic strips are generated by AI based on childrens creative input and parent supervision.
      </p>
      <p>
      Example of AI generated comic strip generated with Azure AI: &nbsp;
      <a href="https://www.instagram.com/p/C-2L7K0qpcY/">https://www.instagram.com/p/C-2L7K0qpcY/</a>
      </p>
    
    </div>
  );
}
